function C = C_batwing(in1,tau,in3)
%C_BATWING
%    C = C_BATWING(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Oct-2017 18:37:46

y = in1(3,:);
C = y;
