function dC = dC_batwing(in1,tau,in3)
%DC_BATWING
%    DC = DC_BATWING(IN1,TAU,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Oct-2017 18:05:07

dy = in1(6,:);
dC = dy;
