function E = energy_batwing(in1,in2)
%ENERGY_BATWING
%    E = ENERGY_BATWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Oct-2017 18:05:01

I1 = in2(6,:);
I2 = in2(7,:);
dth1 = in1(4,:);
dth2 = in1(5,:);
dy = in1(6,:);
g = in2(12,:);
k = in2(8,:);
l1 = in2(1,:);
l2 = in2(2,:);
m1 = in2(3,:);
m2 = in2(4,:);
mb = in2(5,:);
th1 = in1(1,:);
th2 = in1(2,:);
th2_0 = in2(9,:);
y = in1(3,:);
t2 = th1+th2;
t3 = sin(t2);
t10 = sin(th1);
t12 = l1.*t10;
t4 = dth1.*(t12+l2.*t3.*(1.0./2.0))+dth2.*l2.*t3.*(1.0./2.0);
t5 = cos(t2);
t7 = cos(th1);
t6 = dy+dth1.*(l2.*t5.*(1.0./2.0)+l1.*t7)+dth2.*l2.*t5.*(1.0./2.0);
t8 = dy+dth1.*l1.*t7.*(1.0./2.0);
t9 = dth1.^2;
t11 = th2-th2_0;
E = I1.*t9.*(1.0./2.0)+I2.*dth2.^2.*(1.0./2.0)+m1.*(t8.^2+l1.^2.*t9.*t10.^2.*(1.0./4.0)).*(1.0./2.0)+dy.^2.*mb.*(1.0./2.0)+k.*t11.^2.*(1.0./2.0)+m2.*(t4.^2+t6.^2).*(1.0./2.0)+g.*m1.*(t12+y)+g.*mb.*y+g.*m2.*(t12+y+l2.*t3);
