function keypoints = keypoints_batwing(in1,in2)
%KEYPOINTS_BATWING
%    KEYPOINTS = KEYPOINTS_BATWING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    12-Oct-2017 18:37:46

l1 = in2(1,:);
l2 = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
y = in1(3,:);
t2 = cos(th1);
t3 = l1.*t2;
t4 = th1+th2;
t5 = sin(th1);
t6 = l1.*t5;
keypoints = reshape([0.0,y,0.0,t3,t6+y,0.0,t3+l2.*cos(t4),t6+y+l2.*sin(t4),0.0],[3,3]);
